#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V VI

#bspc monitor HDMI-1 -n 1 -d I II III IV V 
#bspc monitor eDP-1 -n 2 -d VI VII VIII IX X

bspc config border_width         8

bspc config focused_border_width 8

bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       true
bspc config focus_follows_pointer  false

bspc config focused_border_color "#A23E48"
#bspc config focused_border_color "#e8751a"

#bspc config normal_border_color "#"
#bspc config active_border_color "#"
#bspc config presel_feedback_color "#"

bspc config initial_polarity    second_child


bspc rule -a Gimp state=floating follow=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Orage state=floating
bspc rule -a Transmission-gtk state=floating
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a dota2 desktop='^6'
bspc rule -a Chromium desktop='^1'
bspc rule -a Codeblocks desktop='^3'
bspc rule -a Octave desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a vlc desktop='^4'
bspc rule -a smplayer desktop='^4'
bspc rule -a Skype desktop='^5'
bspc rule -a Discord desktop='^5'

$HOME/.config/polybar/launch.sh &
